# External gems - updated to plugins in jekyll v3.6
plugins:
 # - jekyll-archives # Sorry, not GitHub pages friendly!
 # - jekyll-assets
 # - autoprefixer-rails
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll/tagging
   - jekyll-tagging-related_posts

# Site settings
title: Lucy Tennyson 
subtitle: Artist
name: Lucy Tennyson
description: Lucy Tennyson art gallery site
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: "https://wealthy-dahlia.cloudvent.net"
logo: "/assets/logo.png"
show_logo: false
headerlogo:
email: a.ward@eyedivision.com

# Build settings
markdown: kramdown

#inter_post_navigation: false
permalink: pretty
highlightjs_theme: "monokai-sublime"

# Image CDN
imagecdn:
  staging: "https://ed-lucytennysonart-dev.imgix.net"
  production: "https://ed-lucytennysonart.imgix.net"

# Collections Example
collections:
    gallery:
        output: true
        permalink: /gallery/:path/
        _hide_content: true

# Defaults Example
defaults:
    -
        scope:
            path: ""
            type: "gallery"
        values:
            layout: "gallery"

# Payment settings
# Environment settings
appurl:
    development: "http://0.0.0.0:4000"
    staging: "http://wealthy-dahlia.cloudvent.net"
    production: "https://www.lucytennyson.co.uk"

# Snipcart API key
# snipcart_api_key:

# PayPal merchant ID
# paypal_id:

# Disqus comments
# disqus_shortname:

# Google analytics
ga_tracking_id: "UA-16735011-17"

# Google Recaptcha used for contact form
recaptcha_site_key: "6LcqySsUAAAAADP9CQARgw8l51B27WwQf0XybfQD"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # SVG icon to use
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:

  - name: Facebook
    icon: icon-facebook_sign
    username:
    url:
    desc: Like on Facebook
    share: true

  - name: Instagram
    icon: icon-instagram
    username:
    url:
    desc: Follow me on Instagram
    share: false

  - name: Twitter
    icon: icon-twitter_sign
    username:
    url:
    desc: Follow us on Twitter
    share: true

  - name: Pinterest
    icon: icon-pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter

protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

