# Global CloudCannon configuration

collections:
  gallery:
    output: true

collection_groups:
  - heading: Gallery
    collections:
      - gallery

# Populates collections for navigation and metadata in the editor
collections_config:
  gallery: 
    icon: image
    sort:
      key: title
    disable_add: false
    image_size: cover  
    image_key: main_image_path
    singular name: Gallery
    singular_key: gallery
    add_options:
      - name: Add Gallery
        icon: add_photo_alternate